# Generated by Django 3.1.2 on 2020-10-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('bodytype', models.CharField(choices=[('coupe', 'Coupe'), ('sedan', 'Sedan'), ('hatchback', 'Hatch Back'), ('suv', 'SUV'), ('sports', 'Sports')], default='sedan', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.manufacturer'),
        ),
    ]
