# Generated by Django 3.1.2 on 2020-10-05 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20201006_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='bodytype',
            new_name='body_type',
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='KL-01-ABC-1234', max_length=40, unique=True)),
                ('purchase_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reg_no'],
            },
        ),
    ]
